baseURL = ""
relativeURLs = true
languageCode = "en"
title = "Teh Lemon"
theme = "mediumish-gohugo-theme"
summaryLength = 25
copyright = "Teh Lemon - All rights reserved"
enableEmoji = true
publishDir = "docs"
#disqusShortname = "your-shortname-here"
googleAnalytics = "UA-62547358-1"
hasCJKLanguage = true
canonifyurls = true

[params]
	### Mine ###
	## The base url used in shortcode img-tl
	imgtlurl = "https://i.tehlemon.com/"
	###	###

  logo = "/images/avatar.jpg"
  description ="Teh Lemon's blog"
  #mailchimp = "you can provide a mailchimp-link here"

[params.author]
  # Commented out to omit the author block above articles
	#name = "Teh Lemon"
  #thumbnail = "/images/avatar2x.jpg"
  #description = ""

[params.index]
  picture = "/images/avatar2x.jpg"
  title = "Teh Lemon"
  subtitle = "I'm a unique placeholder. Working here and there!"
  mdtext = '''
Currently trying to get this blog running, still don't know what the blog will be about!\
**This textblock is a demonstration of the mdtext-param.**\
### This is a markdown heading
'''
  alertbar = false

[params.social]
  github = "teh-lemon"
  #linkedin = "<username>"
  #xing = "<username>"
  #medium = "<username>"
  twitter = "tehlemon"

## Main Menu
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 100
    url = "/"
[[menu.main]]
    name = "Blog"
    weight = 100
    identifier = "blog"
    url = "/blog"
[[menu.main]]
    name = "Notes"
    weight = 100
    identifier = "notes"
    url = "/notes"
[[menu.main]]
    name = "Projects"
    identifier = "projects"
    weight = 200
    url = "/static/projects"