baseURL = ""
relativeURLs = true
languageCode = "en"
title = "Teh Lemon"
theme = "mediumish-gohugo-theme"
summaryLength = 25
copyright = "Teh Lemon"
enableEmoji = true
publishDir = "public"
#disqusShortname = "your-shortname-here"
#googleAnalytics = "UA-62547358-1"
hasCJKLanguage = true
canonifyurls = true

[params]
	### Mine ###
	## The base url used in shortcode img-tl
	imgtlurl = "https://i.tehlemon.com/"
	###	Mine ###

  logo = "/images/lemon.png"
  description ="Teh Lemon's blog"	
  #mailchimp = "you can provide a mailchimp-link here"
  customCSS = ["css/tweaks.css"]

[params.author]
  # Commented out to omit the author block above articles
	name = "Teh Lemon"
  thumbnail = "/images/avatar.jpg"
  description = ""

[params.index]
  picture = "/images/icon.png"
  title = "Teh Lemon"
  subtitle = "I take photos and write code."
  
  # Homepage text
  mdtext = '''
## 📷 [Travel Blogs](/blog)  
&nbsp;
## 🎮 [Dev Diaries](/articles)  
&nbsp;
## 💻 [Dev Portfolio](/static/projects)
&nbsp;

### Github  
#### https://github.com/teh-lemon

### Twitter  
#### https://twitter.com/TehLemon  
'''
  alertbar = false

[params.social]
  #github = "teh-lemon"
  #linkedin = "<username>"
  #xing = "<username>"
  #medium = "<username>"
  #twitter = "tehlemon"
  #instagram = "<username>"

## Main Menu
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 100
    url = "/"
[[menu.main]]
    name = "Articles"
    weight = 100
    identifier = "articles"
    url = "/articles"
[[menu.main]]
    name = "Blog"
    weight = 100
    identifier = "blog"
    url = "/blog"
[[menu.main]]
    name = "Notes"
    weight = 100
    identifier = "notes"
    url = "/notes"
[[menu.main]]
    name = "Projects"
    identifier = "projects"
    weight = 200
    url = "/static/projects"
[[menu.main]]
		name = "RSS"
		identifier = "RSS"
		weight = 200
		url = "/index.xml"
